name: 'Build and Package C# Project'
description: 'Uses msbuild to build and then package a C# project'
inputs:
  csproj:
    description: 'Path to the csproj file to build'
    required: true
  pubxml:
    description: 'Path to the pubxml file'
    required: false
outputs:
  package:
    description: 'The resulting package'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: meh
  color: purple